streamx.blueprints.json-aggregator.configurations.pim.master-namespace=pim
streamx.blueprints.json-aggregator.configurations.pim.optional-namespaces=price,reviews
streamx.blueprints.json-aggregator.configurations.pim.output-namespace=product

streamx.blueprints.json-aggregator.configurations.reviews.master-namespace=review
streamx.blueprints.json-aggregator.configurations.reviews.output-namespace=reviews

streamx.blueprints.json-aggregator.configurations.categories.master-namespace=cat
streamx.blueprints.json-aggregator.configurations.categories.output-namespace=category
