streamx.blueprints.optimized-images-generator.processed-image-path-pattern=.*(png|gif|jpg|jpeg)$
streamx.blueprints.optimized-images-generator.webp-conversion-speed=4
streamx.blueprints.optimized-images-generator.webp-conversion-quality=50
streamx.blueprints.optimized-images-generator.webp-conversion-method=4
streamx.blueprints.optimized-images-generator.webp-conversion-lossless=false
streamx.blueprints.optimized-images-generator.webp-conversion-no-alpha=false